=== jakubjeszke/projekt-htmlcss/xml/index.dtd
<!ELEMENT root (author, definition, media, history, companies, links, media, elevators)>

    <!ENTITY % title_content "title">
    <!ENTITY % text_with_title "title, text">
    <!ENTITY % first_name SYSTEM "external.ent">
    
    <!ELEMENT author (fname, surname, age, birthdate)>
        <!ATTLIST author
            residence CDATA #REQUIRED
            lang CDATA "EN"
            gender CDATA #IMPLIED
            bornIn CDATA #IMPLIED>
        <!ELEMENT fname (#PCDATA)>
        <!ELEMENT surname (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT birthdate (#PCDATA)>

    <!ELEMENT definition (media, %text_with_title;)>
    
    <!ELEMENT history (%text_with_title;)>

    <!ELEMENT companies (%title_content;, country+)>

    <!ELEMENT country (text?, (company*|elevator*|province*))>
        <!ATTLIST country
            name CDATA #REQUIRED
            continent (Europe|Australia|South_America|North_America|Africa|Asia) #REQUIRED>
        <!ELEMENT company (text)>
            <!ATTLIST company
                name CDATA #REQUIRED>
        <!ELEMENT elevator (text)>
            <!ATTLIST elevator
                name CDATA #REQUIRED>
        <!ELEMENT province (city+|elevator+)>
            <!ATTLIST province
                name CDATA #REQUIRED
                kind CDATA #IMPLIED>
            <!ELEMENT city (elevator+)>
                <!ATTLIST city
                    name CDATA #REQUIRED>

    <!ELEMENT links (title?, link+)>
        <!ELEMENT link (#PCDATA)>
            <!ATTLIST link
                source CDATA #REQUIRED>

    <!ELEMENT elevators (country+)>

    <!ELEMENT title (#PCDATA)>

    <!ELEMENT text (#PCDATA)>

    <!ELEMENT media (image+)>
                <!ELEMENT image (#PCDATA)>

    <!ENTITY bannerimg "img/banner.jpg">
    <!ENTITY side1 "img/side1.jpg">
    <!ENTITY side2 "img/side2.jpg">
    <!ENTITY side3 "img/side3.jpg">
    <!ENTITY side4 "img/side4.jpg">
    <!ENTITY side5 "img/side5.jpg">
    <!ENTITY side6 "img/side6.jpg">
    <!ENTITY side7 "img/side7.jpg">
    <!ENTITY side8 "img/side8.jpg">
    <!ENTITY side9 "img/side9.jpg">

=== jakubjeszke/projekt-htmlcss/xml/index_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "index.dtd">
<root>
    <author residence="Polish" lang="PL" gender="male" bornIn="Gdynia">
        <fname>%first_name;</fname>
        <surname>Jeszke></surname>
        <age>19</age>
        <birthdate>2001-04-30</birthdate>
    </author>
    <definition>
        <media>
            <image>&bannerimg;</image>
        </media>
        <title>What is a grain elevator?</title>
        <text>
            Grain elevator is an agrarian facility complex designed to stockpile or store grain. In grain trade, the term "grain elevator" also describes a tower containing a bucket elevator or a pneumatic conveyor, which scoops up grain from a lower level and deposits it in a silo or other storage facility.
        </text>
    </definition>
    <media>
        <image>&side1;</image>
        <image>&side2;</image>
        <image>&side3;</image>
        <image>&side4;</image>
        <image>&side9;</image>
    </media>
    <history>
        <title>History of grain elevators</title>
        <text>
            Both necessity and the prospect of making money gave birth to the steam-powered grain elevator in Buffalo, New York, in 1843. Due to the completion of the Erie Canal in 1825, Buffalo enjoyed a unique position in American geography. It stood at the intersection of two great all-water routes; one extended from New York Harbor, up the Hudson River to Albany, and beyond it, the Port of Buffalo; the other comprised the Great Lakes, which could theoretically take boaters in any direction they wished to go (north to Canada, west to Michigan or Wisconsin, south to Toledo and Cleveland, or east to the Atlantic Ocean). All through the 1830s, Buffalo benefited tremendously from its position. In particular, it was the recipient of most of the increasing quantities of grain (mostly wheat) that was being grown on farms in Ohio and Indiana, and shipped on Lake Erie for trans-shipment to the Erie Canal. If Buffalo had not been there, or when things got backed up there, that grain would have been loaded onto boats at Cincinnati and shipped down the Mississippi River to New Orleans.
            By 1842, Buffalo's port facilities clearly had become antiquated. They still relied upon techniques that had been in use since the European Middle Ages; work teams of stevedores use block and tackles and their own backs to unload or load each sack of grain that had been stored ashore or in the boat's hull. Several days, sometimes even a week, were needed to serve a single grain-laden boat. Grain shipments were going down the Mississippi River, not over the Great Lakes/Erie Canal system.
            A merchant named Joseph Dart, Jr., is generally credited as being the one who adapted Oliver Evans' grain elevator (originally a manufacturing device) for use in a commercial framework (the trans-shipment of grain in bulk from lakers to canal boats), but the actual design and construction of the world's first steam-powered "grain storage and transfer warehouse" was executed by an engineer named Robert Dunbar. Thanks to the historic Dart's Elevator (operational on 1 June 1843), which worked almost seven times faster than its nonmechanized predecessors, Buffalo was able to keep pace with—and thus further stimulate—the rapid growth of American agricultural production in the 1840s and 1850s, but especially after the Civil War, with the coming of the railroads.
            The world's second and third grain elevators were built in Toledo, Ohio, and Brooklyn, New York, in 1847. These fledgling American cities were connected through an emerging international grain trade of unprecedented proportions. Grain shipments from farms in Ohio were loaded onto ships by elevators at Toledo; these ships were unloaded by elevators at Buffalo that shipped their grain to canal boats (and, later, rail cars), which were unloaded by elevators in Brooklyn, where the grain was either distributed to East Coast flour mills or loaded for further shipment to England, the Netherlands, or Germany. This eastern flow of grain, though, was matched by an equally important flow of people and capital in the opposite direction, that is, from east to west. Because of the money to be made in grain production, and of course, because of the existence of an all-water route to get there, increasing numbers of immigrants in Brooklyn came to Ohio, Indiana, and Illinois to become farmers. More farmers meant more prairies turned into farmlands, which in turn meant increased grain production, which of course meant that more grain elevators would have to be built in places such as Toledo, Buffalo, and Brooklyn (and Cleveland, Chicago, and Duluth). Through this loop of productivity set in motion by the invention of the grain elevator, the United States became a major international producer of wheat, corn, and oats.
            In the early 20th century, concern arose about monopolistic practices in the grain elevator industry, leading to testimony before the Interstate Commerce Commission in 1906. This led to several grain elevators being burned down in Nebraska, allegedly in protest.
            Today, grain elevators are a common sight in the grain-growing areas of the world, such as the North_American prairies. Larger terminal elevators are found at distribution centers, such as Chicago and Thunder Bay, Ontario, where grain is sent for processing, or loaded aboard trains or ships to go further afield.
            Buffalo, New York, the world's largest grain port from the 1850s until the first half of the 20th century, once had the United States' largest capacity for the storage of grain in over 30 concrete grain elevators located along the inner and outer harbors. While several are still in productive use, many of those that remain are presently idle. In a nascent trend, some of the city's inactive capacity has recently come back online, with an ethanol plant started in 2007 using one of the previously mothballed elevators to store corn. In the early 20th century, Buffalo's grain elevators inspired modernist architects such as Le Corbusier, who exclaimed, "The first fruits of the new age!" when he first saw them. Buffalo's grain elevators have been documented for the Historic American Engineering Record and added to the National Register of Historic Places. Currently, Enid, Oklahoma, holds the title of most grain storage capacity in the United States.
            In farming communities, each town had one or more small grain elevators that served the local growers. The classic grain elevator was constructed with wooden cribbing and had nine or more larger square or rectangular bins arranged in 3 × 3 or 3 × 4 or 4 × 4 or more patterns. Wooden-cribbed elevators usually had a driveway with truck scale and office on one side, a rail line on the other side, and additional grain-storage annex bins on either side.
            In more recent times with improved transportation, centralized and much larger elevators serve many farms. Some of them are quite large. Two elevators in Kansas (one in Hutchinson and one in Wichita) are half a mile long. The loss of the grain elevators from small towns is often considered a great change in their identity, and efforts to preserve them as heritage structures are made. At the same time, many larger grain farms have their own grain-handling facilities for storage and loading onto trucks.
            Elevator operators buy grain from farmers, either for cash or at a contracted price, and then sell futures contracts for the same quantity of grain, usually each day. They profit through the narrowing "basis", that is, the difference between the local cash price, and the futures price, that occurs at certain times of the year.
            Before economical truck transportation was available, grain elevator operators sometimes used their purchasing power to control prices. This was especially easy, since farmers often had only one elevator within a reasonable distance of their farms. This led some governments to take over the administration of grain elevators. An example of this is the Saskatchewan Wheat Pool. For the same reason, many elevators were purchased by cooperatives.
            In the past, grain elevators sometimes experienced silo explosions. Fine powder from the millions of grains passing through the facility would accumulate and mix with the oxygen in the air. A spark could spread from one floating particle to the other, creating a chain reaction that would destroy the entire structure. (This dispersed-fuel explosion is the mechanism behind fuel-air bombs.) To prevent this, elevators have very rigorous rules against smoking or any other open flame. Many elevators also have various devices installed to maximize ventilation, safeguards against overheating in belt conveyors, legs, bearing, and explosion-proof electrical devices such as electric motors, switches, and lighting.
            Grain elevators in small Canadian communities often had the name of the community painted on two sides of the elevator in large block letters, with the name of the elevator operator emblazoned on the other two sides. This made identification of the community easier for rail operators (and incidentally, for lost drivers and pilots). The old community name often remained on an elevator long after the town had either disappeared or been amalgamated into another community; the grain elevator at Ellerslie, Alberta, remained marked with its old community name until it was demolished, which took place more than 20 years after the village had been annexed by Edmonton.
